2022-04-27 11:50:41,313 -  nornir.core -     INFO -        run() - Running task 'MicroSegmenter' with args {'SegmentationIps': '10.1', 'SpineHostName': 'spine', 'LeafHostname': 'leaf', 'IpDomainName': 'simon'} on 11 hosts
2022-04-27 11:51:42,093 -  nornir.core -     INFO -        run() - Running task 'MicroSegmenter' with args {'SegmentationIps': '10.1', 'SpineHostName': 'spine', 'LeafHostname': 'leaf', 'IpDomainName': 'mon'} on 11 hosts
2022-04-27 11:51:46,789 - nornir.core.task -    ERROR -      start() - Host 'host7.cmh': task 'MicroSegmenter' failed with traceback:
Traceback (most recent call last):
  File "c:\Users\Simon.Edland\Documents\nornir shit\HandyNornir\microsegmenter.py", line 72, in MicroSegmenter
    spineNr=int(neigbor["name"][LenOfNeigborName:LenOfNeigborName+2])
ValueError: invalid literal for int() with base 10: 'ne'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "c:\Users\Simon.Edland\Documents\nornir shit\HandyNornir\microsegmenter.py", line 74, in MicroSegmenter
    spineNr=int(neigbor["name"][LenOfNeigborName:LenOfNeigborName+1])
ValueError: invalid literal for int() with base 10: 'n'

2022-04-27 11:51:46,927 - nornir.core.task -    ERROR -      start() - Host 'host5.cmh': task 'MicroSegmenter' failed with traceback:
Traceback (most recent call last):
  File "c:\Users\Simon.Edland\Documents\nornir shit\HandyNornir\microsegmenter.py", line 72, in MicroSegmenter
    spineNr=int(neigbor["name"][LenOfNeigborName:LenOfNeigborName+2])
ValueError: invalid literal for int() with base 10: 'ne'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "c:\Users\Simon.Edland\Documents\nornir shit\HandyNornir\microsegmenter.py", line 74, in MicroSegmenter
    spineNr=int(neigbor["name"][LenOfNeigborName:LenOfNeigborName+1])
ValueError: invalid literal for int() with base 10: 'n'

2022-04-27 11:51:47,247 - nornir.core.task -    ERROR -      start() - Host 'host6.cmh': task 'MicroSegmenter' failed with traceback:
Traceback (most recent call last):
  File "c:\Users\Simon.Edland\Documents\nornir shit\HandyNornir\microsegmenter.py", line 72, in MicroSegmenter
    spineNr=int(neigbor["name"][LenOfNeigborName:LenOfNeigborName+2])
ValueError: invalid literal for int() with base 10: 'ne'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "c:\Users\Simon.Edland\Documents\nornir shit\HandyNornir\microsegmenter.py", line 74, in MicroSegmenter
    spineNr=int(neigbor["name"][LenOfNeigborName:LenOfNeigborName+1])
ValueError: invalid literal for int() with base 10: 'n'

2022-04-27 11:51:47,303 - nornir.core.task -    ERROR -      start() - Host 'host8.cmh': task 'MicroSegmenter' failed with traceback:
Traceback (most recent call last):
  File "c:\Users\Simon.Edland\Documents\nornir shit\HandyNornir\microsegmenter.py", line 72, in MicroSegmenter
    spineNr=int(neigbor["name"][LenOfNeigborName:LenOfNeigborName+2])
ValueError: invalid literal for int() with base 10: 'ne'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "c:\Users\Simon.Edland\Documents\nornir shit\HandyNornir\microsegmenter.py", line 74, in MicroSegmenter
    spineNr=int(neigbor["name"][LenOfNeigborName:LenOfNeigborName+1])
ValueError: invalid literal for int() with base 10: 'n'

2022-04-27 11:51:47,752 - nornir.core.task -    ERROR -      start() - Host 'host10.cmh': task 'MicroSegmenter' failed with traceback:
Traceback (most recent call last):
  File "c:\Users\Simon.Edland\Documents\nornir shit\HandyNornir\microsegmenter.py", line 72, in MicroSegmenter
    spineNr=int(neigbor["name"][LenOfNeigborName:LenOfNeigborName+2])
ValueError: invalid literal for int() with base 10: 'ne'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "c:\Users\Simon.Edland\Documents\nornir shit\HandyNornir\microsegmenter.py", line 74, in MicroSegmenter
    spineNr=int(neigbor["name"][LenOfNeigborName:LenOfNeigborName+1])
ValueError: invalid literal for int() with base 10: 'n'

2022-04-27 11:51:47,824 - nornir.core.task -    ERROR -      start() - Host 'host4.cmh': task 'MicroSegmenter' failed with traceback:
Traceback (most recent call last):
  File "c:\Users\Simon.Edland\Documents\nornir shit\HandyNornir\microsegmenter.py", line 72, in MicroSegmenter
    spineNr=int(neigbor["name"][LenOfNeigborName:LenOfNeigborName+2])
ValueError: invalid literal for int() with base 10: 'ne'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "c:\Users\Simon.Edland\Documents\nornir shit\HandyNornir\microsegmenter.py", line 74, in MicroSegmenter
    spineNr=int(neigbor["name"][LenOfNeigborName:LenOfNeigborName+1])
ValueError: invalid literal for int() with base 10: 'n'

2022-04-27 11:51:47,848 - nornir.core.task -    ERROR -      start() - Host 'host11.cmh': task 'MicroSegmenter' failed with traceback:
Traceback (most recent call last):
  File "c:\Users\Simon.Edland\Documents\nornir shit\HandyNornir\microsegmenter.py", line 72, in MicroSegmenter
    spineNr=int(neigbor["name"][LenOfNeigborName:LenOfNeigborName+2])
ValueError: invalid literal for int() with base 10: 'ne'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "c:\Users\Simon.Edland\Documents\nornir shit\HandyNornir\microsegmenter.py", line 74, in MicroSegmenter
    spineNr=int(neigbor["name"][LenOfNeigborName:LenOfNeigborName+1])
ValueError: invalid literal for int() with base 10: 'n'

2022-04-27 11:51:47,870 - nornir.core.task -    ERROR -      start() - Host 'host9.cmh': task 'MicroSegmenter' failed with traceback:
Traceback (most recent call last):
  File "c:\Users\Simon.Edland\Documents\nornir shit\HandyNornir\microsegmenter.py", line 72, in MicroSegmenter
    spineNr=int(neigbor["name"][LenOfNeigborName:LenOfNeigborName+2])
ValueError: invalid literal for int() with base 10: 'ne'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "c:\Users\Simon.Edland\Documents\nornir shit\HandyNornir\microsegmenter.py", line 74, in MicroSegmenter
    spineNr=int(neigbor["name"][LenOfNeigborName:LenOfNeigborName+1])
ValueError: invalid literal for int() with base 10: 'n'

2022-04-27 11:51:48,148 - nornir.core.task -    ERROR -      start() - Host 'host3.cmh': task 'MicroSegmenter' failed with traceback:
Traceback (most recent call last):
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "c:\Users\Simon.Edland\Documents\nornir shit\HandyNornir\microsegmenter.py", line 103, in MicroSegmenter
    relevantSubbnet=listOfSubbnets[SpineNr-1][leafNr-1]
UnboundLocalError: local variable 'leafNr' referenced before assignment

2022-04-27 11:51:48,340 - nornir.core.task -    ERROR -      start() - Host 'host2.cmh': task 'MicroSegmenter' failed with traceback:
Traceback (most recent call last):
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "c:\Users\Simon.Edland\Documents\nornir shit\HandyNornir\microsegmenter.py", line 103, in MicroSegmenter
    relevantSubbnet=listOfSubbnets[SpineNr-1][leafNr-1]
UnboundLocalError: local variable 'leafNr' referenced before assignment

2022-04-27 11:51:48,679 - nornir.core.task -    ERROR -      start() - Host 'host1.cmh': task 'MicroSegmenter' failed with traceback:
Traceback (most recent call last):
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "c:\Users\Simon.Edland\Documents\nornir shit\HandyNornir\microsegmenter.py", line 103, in MicroSegmenter
    relevantSubbnet=listOfSubbnets[SpineNr-1][leafNr-1]
UnboundLocalError: local variable 'leafNr' referenced before assignment

2022-04-27 11:52:03,916 -  nornir.core -     INFO -        run() - Running task 'MicroSegmenter' with args {'SegmentationIps': '10.1', 'SpineHostName': 'spine', 'LeafHostname': 'leaf', 'IpDomainName': 'simon'} on 11 hosts
2022-04-27 11:53:48,558 -  nornir.core -     INFO -        run() - Running task 'MicroSegmenter' with args {'SegmentationIps': '10.1', 'SpineHostName': 'spine', 'LeafHostname': 'leaf', 'IpDomainName': 'lolol'} on 11 hosts
