2022-04-22 10:15:00,546 -  nornir.core -     INFO -        run() - Running task 'MicroSegmenter' with args {} on 10 hosts
2022-04-22 10:15:24,707 -  nornir.core -     INFO -        run() - Running task 'SaveRunningToStart' with args {} on 10 hosts
2022-04-22 10:15:44,383 -  nornir.core -     INFO -        run() - Running task 'SaveRunningToStart' with args {} on 10 hosts
2022-04-22 10:34:34,382 -  nornir.core -     INFO -        run() - Running task 'MicroSegmenter' with args {} on 11 hosts
2022-04-22 10:35:00,410 -  nornir.core -     INFO -        run() - Running task 'SaveRunningToStart' with args {} on 11 hosts
2022-04-22 11:01:54,438 -  nornir.core -     INFO -        run() - Running task 'MicroSegmenter' with args {} on 12 hosts
2022-04-22 11:05:30,575 -  nornir.core -     INFO -        run() - Running task 'MicroSegmenter' with args {} on 12 hosts
2022-04-22 11:06:25,986 -  nornir.core -     INFO -        run() - Running task 'MicroSegmenter' with args {} on 12 hosts
2022-04-22 11:07:37,013 -  nornir.core -     INFO -        run() - Running task 'MicroSegmenter' with args {} on 12 hosts
2022-04-22 11:10:57,760 -  nornir.core -     INFO -        run() - Running task 'MicroSegmenter' with args {} on 12 hosts
2022-04-22 11:12:58,250 -  nornir.core -     INFO -        run() - Running task 'MicroSegmenter' with args {} on 12 hosts
2022-04-22 11:15:30,888 -  nornir.core -     INFO -        run() - Running task 'MicroSegmenter' with args {} on 12 hosts
2022-04-22 11:17:46,959 -  nornir.core -     INFO -        run() - Running task 'MicroSegmenter' with args {} on 12 hosts
2022-04-22 11:33:53,251 -  nornir.core -     INFO -        run() - Running task 'MicroSegmenter' with args {} on 13 hosts
2022-04-22 11:33:56,392 - nornir.core.task -    ERROR -      start() - Host 'host13.cmh': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 935, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\client.py", line 435, in connect
    self._auth(
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\client.py", line 766, in _auth
    raise saved_exception
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\client.py", line 753, in _auth
    self._transport.auth_password(username, password)
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\transport.py", line 1563, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\auth_handler.py", line 258, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\nornir_netmiko\tasks\netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\nornir_netmiko\connections\netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\cisco\cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 350, in __init__
    self._open()
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 355, in _open
    self.establish_connection()
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 972, in establish_connection
    raise NetmikoAuthenticationException(msg)
netmiko.ssh_exception.NetmikoAuthenticationException: Authentication to device failed.

Common causes of this problem are:
1. Invalid username and password
2. Incorrect SSH-key file
3. Connecting to the wrong device

Device settings: cisco_ios 13.13.13.13:22


Authentication failed.

2022-04-22 11:33:56,393 - nornir.core.task -    ERROR -      start() - Host 'host13.cmh': task 'MicroSegmenter' failed with traceback:
Traceback (most recent call last):
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "c:\Users\Simon.Edland\Documents\nornir shit\HandyNornir\microsegmenter.py", line 30, in MicroSegmenter
    node.host["intf"] = node.run(task=netmiko_send_command, command_string=("sh cdp nei de")).result
  File "C:\Users\Simon.Edland\AppData\Local\Programs\Python\Python310\lib\site-packages\nornir\core\task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netmiko_send_command (failed)


2022-04-22 11:35:51,814 -  nornir.core -     INFO -        run() - Running task 'MicroSegmenter' with args {} on 13 hosts
2022-04-22 12:14:32,705 -  nornir.core -     INFO -        run() - Running task 'MicroSegmenter' with args {} on 14 hosts
2022-04-22 12:16:15,885 -  nornir.core -     INFO -        run() - Running task 'MicroSegmenter' with args {} on 14 hosts
2022-04-22 12:30:58,331 -  nornir.core -     INFO -        run() - Running task 'MicroSegmenter' with args {} on 14 hosts
2022-04-22 12:31:44,778 -  nornir.core -     INFO -        run() - Running task 'SaveRunningToStart' with args {} on 14 hosts
2022-04-22 12:32:10,827 -  nornir.core -     INFO -        run() - Running task 'SaveRunningToStart' with args {} on 14 hosts
